// Generated by scripts/generate-release-train-config.py. Edit ReleaseTrains.json.
enum ReleaseTrainCatalogue {
    static let values: [String: [String: String]] = [
        "stable": [
            "applicationSupportDirectory": "SpeakApp",
            "iosBundleIdentifier": "com.justspeaktoit.ios",
            "directMacBundleIdentifier": "com.justspeaktoit.mac",
            "storeMacBundleIdentifier": "com.justspeaktoit.mac.appstore",
            "directMacProductName": "JustSpeakToIt",
            "storeMacProductName": "JustSpeakToItAppStore",
            "displayName": "Just Speak to It",
            "iosAppGroup": "group.com.justspeaktoit.ios",
            "watchAppGroup": "group.com.justspeaktoit.watch",
            "iosCloudContainer": "iCloud.com.justspeaktoit.ios",
            "macCloudContainer": "iCloud.com.justspeaktoit",
            "urlScheme": "justspeaktoit",
            "transportServiceType": "_speaktransport._tcp",
            "feedURL": "https://justspeaktoit.com/appcast.xml",
            "arm64FeedURL": "https://justspeaktoit.com/appcast-arm64.xml",
            "cliDownloadURL": "https://github.com/crmitchelmore/justspeaktoit/releases/latest/download/",
            "cliExecutableName": "speak",
            "macKVStoreIdentifier": "com.justspeaktoit",
            "iosKVStoreIdentifier": "com.justspeaktoit.ios"
        ],
        "alpha": [
            "applicationSupportDirectory": "SpeakAppAlpha",
            "iosBundleIdentifier": "com.justspeaktoit.ios.alpha",
            "directMacBundleIdentifier": "com.justspeaktoit.mac.alpha",
            "storeMacBundleIdentifier": "com.justspeaktoit.mac.appstore.alpha",
            "directMacProductName": "JustSpeakToItAlpha",
            "storeMacProductName": "JustSpeakToItAlphaAppStore",
            "displayName": "Just Speak to It Alpha",
            "iosAppGroup": "group.com.justspeaktoit.ios.alpha",
            "watchAppGroup": "group.com.justspeaktoit.watch.alpha",
            "iosCloudContainer": "iCloud.com.justspeaktoit.ios.alpha",
            "macCloudContainer": "iCloud.com.justspeaktoit.alpha",
            "urlScheme": "justspeaktoit-alpha",
            "transportServiceType": "_speakalpha._tcp",
            "feedURL": "https://justspeaktoit.com/alpha/appcast.xml",
            "arm64FeedURL": "https://justspeaktoit.com/alpha/appcast-arm64.xml",
            "cliDownloadURL": "https://justspeaktoit.com/alpha/cli/",
            "cliExecutableName": "speak-alpha",
            "macKVStoreIdentifier": "com.justspeaktoit.alpha",
            "iosKVStoreIdentifier": "com.justspeaktoit.ios.alpha"
        ]
    ]
}
