#!/usr/bin/env python3
"""Generate the dependency-free Swift projection of the canonical train catalogue."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'Sources/SpeakCore/Resources/ReleaseTrains.json'
TARGET = ROOT / 'Sources/SpeakCore/ReleaseTrainCatalogue.swift'


def rendered():
    catalogue = json.loads(SOURCE.read_text())
    lines = ['// Generated by scripts/generate-release-train-config.py. Edit ReleaseTrains.json.',
             'enum ReleaseTrainCatalogue {', '    static let values: [String: [String: String]] = [']
    for train_index, (train, values) in enumerate(catalogue.items()):
        lines.append(f'        "{train}": [')
        for index, (key, value) in enumerate(values.items()):
            comma = ',' if index < len(values) - 1 else ''
            lines.append(f'            {json.dumps(key)}: {json.dumps(value)}{comma}')
        lines.append('        ]' + (',' if train_index < len(catalogue) - 1 else ''))
    lines.extend(['    ]', '}', ''])
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    options = parser.parse_args()
    result = rendered()
    if options.check:
        if not TARGET.exists() or TARGET.read_text() != result:
            raise SystemExit('Release train Swift catalogue is stale; run scripts/generate-release-train-config.py')
    else:
        TARGET.write_text(result)
