#!/bin/bash
# Generate a Sparkle appcast from a GitHub release asset.
# Usage: ./scripts/generate-appcast.sh <version> <build-number> <dmg-path> <private-key-base64> [release-notes-html] [feed-url]
#
# Two feeds are generated per release (issue #774): the legacy feed
# (https://justspeaktoit.com/appcast.xml, universal DMG, which every Mac and
# every existing install can run) and the Apple Silicon feed
# (https://justspeaktoit.com/appcast-arm64.xml, arm64-only DMG). The enclosure
# URL is derived from the DMG's file name, so each feed points at its own asset.

set -e

VERSION="$1"
BUILD_NUMBER="$2"
DMG_PATH="$3"
PRIVATE_KEY_BASE64="$4"
RELEASE_NOTES_HTML_PATH="${5:-}"
FEED_URL="${6:-https://justspeaktoit.com/appcast.xml}"

if [ -z "$VERSION" ] || [ -z "$BUILD_NUMBER" ] || [ -z "$DMG_PATH" ] || [ -z "$PRIVATE_KEY_BASE64" ]; then
    echo "Usage: $0 <version> <build-number> <dmg-path> <private-key-base64>"
    echo "  version: Marketing version (e.g., 0.5.0) for display"
    echo "  build-number: Build number (e.g., 43) for Sparkle comparison"
    exit 1
fi

# Get file info
FILE_SIZE=$(stat -f%z "$DMG_PATH" 2>/dev/null || stat --format=%s "$DMG_PATH")
PUB_DATE=$(date -R)
DMG_NAME=$(basename "$DMG_PATH")

# Create temp file for private key
PRIVATE_KEY_FILE=$(mktemp)
# Ensure private key is cleaned up on exit (success or failure)
trap 'rm -f "$PRIVATE_KEY_FILE"' EXIT

# The Sparkle private key is a base64-encoded string (44 chars)
# sign_update expects the raw string, NOT base64-decoded bytes
echo "$PRIVATE_KEY_BASE64" > "$PRIVATE_KEY_FILE"
echo "Private key written (raw, not decoded)" >&2

# Find Sparkle's sign_update tool
SIGN_UPDATE=""
if [ -f ".build/artifacts/sparkle/Sparkle/bin/sign_update" ]; then
    SIGN_UPDATE=".build/artifacts/sparkle/Sparkle/bin/sign_update"
elif command -v sign_update &> /dev/null; then
    SIGN_UPDATE="sign_update"
else
    # Last resort only (CI always has the SwiftPM artifact bundle): the
    # tools run with the private key on disk, so the download must fail on
    # HTTP errors and match a pinned digest before anything is extracted.
    echo "Warning: sign_update not found, downloading Sparkle tools..." >&2
    SPARKLE_VERSION="2.8.1"
    SPARKLE_TOOLS_SHA256="5cddb7695674ef7704268f38eccaee80e3accbf19e61c1689efff5b6116d85be"
    SPARKLE_TOOLS_DIR="$(mktemp -d)"
    curl --fail -sL "https://github.com/sparkle-project/Sparkle/releases/download/${SPARKLE_VERSION}/Sparkle-${SPARKLE_VERSION}.tar.xz" \
        -o "$SPARKLE_TOOLS_DIR/Sparkle.tar.xz"
    ACTUAL_SHA256="$(shasum -a 256 "$SPARKLE_TOOLS_DIR/Sparkle.tar.xz" | awk '{print $1}')"
    if [ "$ACTUAL_SHA256" != "$SPARKLE_TOOLS_SHA256" ]; then
        echo "Error: Sparkle ${SPARKLE_VERSION} tools digest mismatch ($ACTUAL_SHA256); refusing to run a signing tool that does not match the pin" >&2
        exit 1
    fi
    tar xJ -C "$SPARKLE_TOOLS_DIR" -f "$SPARKLE_TOOLS_DIR/Sparkle.tar.xz"
    SIGN_UPDATE="$SPARKLE_TOOLS_DIR/bin/sign_update"
fi

# Generate EdDSA signature
# For newer Sparkle keys, use --ed-key-file with stdin (-) as recommended
# sign_update outputs the signature attributes that need to be extracted
echo "Running sign_update..." >&2
echo "SIGN_UPDATE path: $SIGN_UPDATE" >&2
echo "DMG_PATH: $DMG_PATH" >&2
ls -la "$SIGN_UPDATE" >&2 || echo "sign_update not found" >&2

# Run sign_update and capture output
set +e
"$SIGN_UPDATE" --ed-key-file "$PRIVATE_KEY_FILE" "$DMG_PATH" > /tmp/sign_output.txt 2>&1
SIGN_EXIT_CODE=$?
set -e

echo "sign_update exit code: $SIGN_EXIT_CODE" >&2
echo "sign_update output:" >&2
cat /tmp/sign_output.txt >&2

SIGNATURE=$(grep "sparkle:edSignature" /tmp/sign_output.txt | sed 's/.*sparkle:edSignature="\([^"]*\)".*/\1/' || true)

if [ -z "$SIGNATURE" ]; then
    echo "Error: Failed to generate signature" >&2
    exit 1
fi

# GitHub release download URL
DOWNLOAD_URL="https://github.com/crmitchelmore/justspeaktoit/releases/download/mac-v${VERSION}/${DMG_NAME}"

# Prefer the detailed release notes generated by Luna for Sparkle's in-app update UI.
if [ -n "$RELEASE_NOTES_HTML_PATH" ] && [ -s "$RELEASE_NOTES_HTML_PATH" ]; then
    RELEASE_NOTES_HTML=$(cat "$RELEASE_NOTES_HTML_PATH")
else
    # Retain a deterministic fallback for manual use and model/API outages.
    MAC_RELEASE_NOTES_PATTERN="\\[mac\\]|\\(mac\\)"
    LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
    if [ -n "$LAST_TAG" ]; then
        echo "Generating fallback release notes from commits since $LAST_TAG" >&2
        RELEASE_NOTES=$(git log "$LAST_TAG"..HEAD --pretty=format:"<li>%s</li>" --grep="$MAC_RELEASE_NOTES_PATTERN" --extended-regexp 2>/dev/null | head -20 || echo "<li>Bug fixes and improvements</li>")
    else
        RELEASE_NOTES="<li>Initial release</li>"
    fi

    if [ -z "$RELEASE_NOTES" ]; then
        RELEASE_NOTES="<li>Bug fixes and improvements</li>"
    fi
    RELEASE_NOTES_HTML="<h2>What's New in ${VERSION}</h2><ul>${RELEASE_NOTES}</ul>"
fi

# Generate appcast XML
# IMPORTANT: sparkle:version MUST match the app's CFBundleVersion (build number)
# for Sparkle to correctly detect updates. sparkle:shortVersionString is for display only.
cat << EOF
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Just Speak to It Updates</title>
    <link>${FEED_URL}</link>
    <description>Most recent updates to Just Speak to It</description>
    <language>en</language>
    <item>
      <title>Version ${VERSION}</title>
      <sparkle:version>${BUILD_NUMBER}</sparkle:version>
      <sparkle:shortVersionString>${VERSION}</sparkle:shortVersionString>
      <sparkle:fullReleaseNotesLink>https://github.com/crmitchelmore/justspeaktoit/releases</sparkle:fullReleaseNotesLink>
      <pubDate>${PUB_DATE}</pubDate>
      <description><![CDATA[
        ${RELEASE_NOTES_HTML}
      ]]></description>
      <enclosure
        url="${DOWNLOAD_URL}"
        sparkle:edSignature="${SIGNATURE}"
        length="${FILE_SIZE}"
        type="application/octet-stream"
        sparkle:phasedRolloutInterval="86400"/>
      <sparkle:minimumSystemVersion>14.0</sparkle:minimumSystemVersion>
    </item>
  </channel>
</rss>
EOF
